/*
-- Query: select * from govtschemedata
LIMIT 0, 1000

-- Date: 2016-08-04 14:41
*/
INSERT INTO `govtschemedata` (`id`,`createTime`,`description1`,`description2`,`editTime`,`isactive`,`schemename`,`startdate`,`state`,`webpageurl`) VALUES (1,'2013-12-12 00:00:00','Make in India was launched against the backdrop of this crisis,& quickly became a rallying cry for India’s innumerable stakeholders and partners.','Make in India is opening investment doors. Multiple enterprises are adopting its mantra. The world’s largest democracy is well on its way to becoming the world’s most powerful economy.','2014-10-01 00:00:00',1,'MAKE IN INDIA','2014-12-12 00:00:00','Active','http://www.makeinindia.com/');
INSERT INTO `govtschemedata` (`id`,`createTime`,`description1`,`description2`,`editTime`,`isactive`,`schemename`,`startdate`,`state`,`webpageurl`) VALUES (2,'2014-06-12 00:00:00','Swachh Bharat Abhiyan is a national campaign by the Government of India, covering 4,041 statutory cities and towns, to clean the streets, roads and infrastructure of the country.','The campaign was officially launched on 2 October 2014 at Rajghat, New Delhi.It is India\'s biggest ever cleanliness drive and 3 million government employees and school and college students of India participated in this event.','2014-12-12 00:00:00',1,'SWACHH BHARAT','2014-10-02 00:00:00','Active','http://swachhbharaturban.gov.in');
INSERT INTO `govtschemedata` (`id`,`createTime`,`description1`,`description2`,`editTime`,`isactive`,`schemename`,`startdate`,`state`,`webpageurl`) VALUES (3,'2015-07-01 00:00:00','Digital India programme, the government is taking a big step forward to transform the country into a digitally empowered knowledge economy,Includes various schemes worth over Rs 1 lakh crore like Digital Locker, e-eduction, e-health.','Aims to ensure that government services are available to citizens electronically and people get benefited from the latest information and communication technology','2015-09-01 00:00:00',1,'DIGITAL INDIA PROGRAMME','2015-07-01 00:00:00','Active','http://digitalindia.gov.in');
INSERT INTO `govtschemedata` (`id`,`createTime`,`description1`,`description2`,`editTime`,`isactive`,`schemename`,`startdate`,`state`,`webpageurl`) VALUES (4,'2014-08-28 00:00:00','PMJDY is India\'s National Mission for Financial Inclusion to ensure access to financial services, namely Banking Savings & Deposit Accounts, Remittance, Credit, Insurance, Pension in an affordable manner.','National Mission for Financial Inclusion to ensure access to financial services, namely Banking Savings & Deposit Accounts, Remittance, Credit, Insurance, Pension in an affordable manner','2015-08-28 00:00:00',1,'Pradhan Mantri Jan Dhan Yojana','2014-08-28 00:00:00','Active','www.pmjdy.gov.in');
